### PR TITLE
Apply patch for icpc

### LINKED ISSUE #77: Failure with Intel ICPC 19.1.3 on MacOS
I am getting the following error following the examples on the Readme:
```
path/variant_example/3rdparty/variant/include/mpark/variant.hpp(1613): error: parameter pack "Ts" was referenced but not expanded
          typename Front = lib::type_pack_element_t<0, Ts...>,
                           ^

compilation aborted for path/variant_example/hello_world.cpp (code 2)
make[2]: *** [CMakeFiles/hello-world.dir/hello_world.cpp.o] Error 2
make[1]: *** [CMakeFiles/hello-world.dir/all] Error 2
```
The intel C++ compiler ties to the underlying apple-clang compiler and I can see that icpc is setting "___clang___".
```
cheddar:variant_example: $ icpc -dM -E -std=c++11 -x c++ -I 3rdparty/variant/include ./hello_world.cpp | grep -yR __clang__
(standard input):#define __clang__ 1
(standard input):#define __clang__ 1
```

I'm not sure if this is an Intel error or not since by default Intel ties to the underlying apple-clang C/C++ compiler.

Thanks for looking, 
Tony

### PR DESCRIPTION
**Pull request by sbolding-LANL**
icpc in some way utilizes the preprocessor of the associated "developer
tools" used by the compiler. This leads to, in some cases, a
preprocessor claiming support for `__tuple_element_packs`, even though
icpc (as of version 21.1) can't actually parse such code.  Just use the
MPARK_TUPLE_ELEMENT_PACK impl with __icc until icpc supports it.

Fixes #77

FYI, even with this patch, icpc 19.1.3  fails to compile one of the mpark tests (I couldn't seem to clone the llvm tests on my system, but probably because of our network).  All tests but this one compiled and passed:

```
/Users/sbolding/codes/mcnp6/build/git-submodule-packages/mpark-variant/test/assign.fwd.cpp(53): error: static assertion failed with "variant<short, long> v; v = 42;"
    static_assert(std::is_assignable<mpark::variant<short, long>, int>{},
```

I imagine any Intel users are already working around this if they needed to SFINAE on something like this, so I am OK with this limitation until the new Intel clang front ends are widely available :), but without this patch we can't build at all on Catalina.

### CODE REVIEW

File: include/mpark/config.hpp [hunk 1]
```diff
@@ -50,7 +50,7 @@
 #define MPARK_BUILTIN_UNREACHABLE
 #endif
 
-#if __has_builtin(__type_pack_element)
+#if __has_builtin(__type_pack_element) && !(defined(__ICC))
```
Comment (ax3l) [inline include/mpark/config.hpp:53]: Following this quick check on Linux, I think your problem is most likely macOS specific:
  https://godbolt.org/z/6v5GMxz4v

I would this recommend to limit this patch to ICC + Apple:
```suggestion
+#if __has_builtin(__type_pack_element) && !(defined(__ICC) && defined(__APPLE__))
```

Comment (ax3l) [reply include/mpark/config.hpp:53]: Responded [here](https://github.com/spack/spack/pull/22727#discussion_r605978256):

> I originally thought this was an Apple specific issue, but I think it is just dependent on the toolchain icc is using (I may be saying this wrong; I really don't understand how Intel uses the underlying toolchain's preprocessor).  The reason this is passing on Linux is that with the gcc10.2 toolchain, `__has_builtin(__type_pack_element)` is evaluating to false: https://godbolt.org/z/zeevevqcW
>
> My concern is that if in the future GCC adds `__type_pack_element` support, then Intel with that tool-chain will start failing.  It may also fail on linux if someone compiles using an LLVM toolchain: [intel doc on setting clang](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/compatibility-options/clangxx-name.html.)  Other than compile time, I don't think there is much risk in always using mpark's implementation of type_pack_element.  
>
> But I am open to maybe making it `__clang__` specific for now and dealing with it in the future when it arises :) 

Ok, then let's keep this for ICC in general.

**Comment by ax3l** [comment]
@mpark any news on this one? :)

**Comment by mpark** [comment]
Read through a bit of the history and issue... it really doesn't seem like something I want to dig deep into.
Going to merge this for now and maybe come back if there are other ICC issues that come up.
